Develop
ttiverson3/taipei-day-trip-website pull request #3
Opened 2021-04-29 18:23 UTC by ttiverson3

偉豪
http://18.219.166.25:3000/

2021-04-30 02:06 UTC, cwpeng requested changes
捲動到底部的時候，無法載入更多的資訊 ~~~

2021-04-30 09:39 UTC, ttiverson3 commented
已修正再麻煩老師一下，謝謝老師～

2021-04-30 17:20 UTC, ttiverson3 commented
已修正～
http://18.116.177.114:3000/

2021-05-01 03:51 UTC, cwpeng commented
後端連線看起來是斷掉了，請恢復後提出 Review 要求哦 ~

2021-05-01 06:52 UTC, ttiverson3 commented
不好意思，再麻煩老師了
http://18.116.177.114:3000/

2021-05-01 07:08 UTC, cwpeng approved these changes
OK，這樣就可以嘍 ~

2021-05-01 07:56 UTC, merged